// Gabarit du contrat de syndic REAL31 - GENERE, NE PAS EDITER A LA MAIN.
//
// Produit par `node scripts/convertir-gabarit-contrat.mjs` a partir du classeur
// « Contrat de Syndic.xlsx » (SharePoint Reality > Documents), celui-la meme que le flow
// PowerApps MYTHEC remplissait via l'Office Script ContratReplace.
//
// Le contrat s'imprime sur DEUX COLONNES independantes : chaque liste ci-dessous est un
// flux vertical, rendu cote a cote. Les valeurs variables sont des placeholders `[Xxx]`
// resolus a l'affichage.
//
// Le contrat type evolue avec la loi (le texte cite les decrets de 2015, 2020 et 2025) :
// quand le cabinet met a jour son classeur, on relance le script et on relit le diff.
//
// 2 blocs pleine largeur, 117 a gauche, 81 a droite,
// 65 placeholders distincts.

/** Un bloc : un paragraphe, ou les cellules d'une ligne de grille tarifaire. */
export type BlocGabarit = string | readonly string[];

/** Blocs sur TOUTE la largeur, en tete de document (titre, mention des decrets). */
export const GABARIT_PLEINE_LARGEUR: readonly string[] = [
  "CONTRAT DE SYNDIC \"TOUT SAUF\" N°",
  "(Contrat type prévu à l’article 18-1 A de la loi n° 65-557 du 10 juillet 1965 modifiée fixant le statut de la copropriété des immeubles bâtis et à l’article 29 du décret n° 67-223 du 17 mars 1967 pris pour son application, modifié par le décret n° 2015-342 du 26 mars 2015, le décret n° 2020-834 du 2 juillet 2020 et le décret n°2025-1292 du 22 décembre 2025.)",
] as const;

/** Colonne de gauche du contrat, de haut en bas. */
export const GABARIT_GAUCHE: readonly BlocGabarit[] = [
  "ENTRE LES SOUSSIGNÉS PARTIES",
  "1. D’une part :\nLe syndicat des copropriétaires de l’immeuble sis à l’adresse suivante :\n[Coproprietes.Adresse1] [Coproprietes.Adresse2] [Coproprietes.Adresse3] [Coproprietes.CP] [Coproprietes.Ville]\n\nNuméro d’immatriculation [Coproprietes.RegistreNumero]\n\nReprésenté pour le présent contrat par \nagissant en exécution de la décision de l’assemblée générale des copropriétaires du [DateAG]\n\nTitulaire d’un contrat d’assurance responsabilité civile souscrit le [Coproprietes.DateAssurance] auprès de : [Coproprietes.Assurance]\n\net\n\n2. D’autre part :\nLe syndic désigné par l’assemblée générale en date du [DateAG]\nLa SAS REAL 31\n[Coproprietes.Agence]\nimmatriculée au registre du commerce et des sociétés de Versailles sous le n° 479 696 767, représentée par Emmanuel LOPES en sa qualité de Dirigeant.\n\nTitulaire de la carte professionnelle n° CPI 7801 2016 000 014 479, permettant l’exercice de l’activité de : transaction sur immeubles et fonds de commerces * gestion immobilière * Syndic de copropriété, délivrée par la CCI Paris Île-de-France le 25 Novembre 2025. Garanti par GALIAN-SMABTP, 89 rue la Boétie – 75008 Paris sous la référence 110891J, pour un montant de 10 106 000€ pour l’activité de Syndic de Copropriété, contrat souscrit le 13/12/2004 et couvrant la zone géographique suivante : République Française (France Métropolitaine, DROM-COM). \n\nAssuré(e) en responsabilité civile professionnelle par MMA IARD – 14 boulevard Marie et Alexandre Oyon – 72030 Le Mans Cedex 9 sous le contrat n° 127 103 751 souscrit le 13/12/2004, couvrant la zone géographique suivante : République Française (France Métropolitaine, DROM-COM).\nAdhérent à la Fédération Nationale de l’Immobilier (FNAIM), ayant le titre professionnel de Dirigeant obtenu en France et visé ci-dessus\nNuméro individuel d’identification à la TVA FR : FR59 479 696 767\nIntermédiaire immatriculé à l’ORIAS sous le numéro 15000214\n\nIl a été convenu ce qui suit :",
  "4. RESILIATION DU CONTRAT A L'INITIATIVE DU SYNDIC",
  "La résiliation du contrat doit être fondée sur une inexécution suffisamment grave reprochée par le syndic au syndicat des copropriétaires.\n\nLe syndic doit notifier son intention au président du conseil syndical, et à défaut à chaque copropriétaire, en précisant la ou les inexécutions reprochées par le syndic au syndicat des copropriétaires.\n\nIl convoque dans un délai qui ne peut être inférieur à deux mois à compter de cette notification une assemblée générale, en inscrivant à l'ordre du jour la question de la désignation d'un nouveau syndic.\n\nLa résiliation prend effet au plus tôt un jour franc après la tenue de l'assemblée générale.",
  "5. NOUVELLE DESIGNATION DU SYNDIC",
  "A la fin du présent contrat, l’assemblée générale des copropriétaires procède à la désignation du syndic de la copropriété. Un nouveau contrat, soumis à l’approbation de l’assemblée générale, est conclu avec le syndic désigné à nouveau ou avec le nouveau syndic.\n \nLorsqu'il est envisagé de désigner un nouveau syndic, il peut être mis fin au présent contrat, de manière anticipée et sans indemnité, dès lors que la question du changement de syndic et de la date de fin du présent contrat sont inscrites à l'ordre du jour d'une assemblée générale convoquée dans les trois mois précédant le terme du présent contrat.\n\nLe syndic qui ne souhaite pas être désigné à nouveau doit en informer le président du conseil syndical au moins trois mois avant la tenue de cette assemblée générale.\n\nL’assemblée générale appelée à se prononcer sur cette désignation est précédée d’une mise en concurrence de plusieurs projets de contrat, qui s’effectue dans les conditions précisées à l’article 21 de la loi du 10 juillet 1965.",
  "6. FICHE SYNTHETIQUE DE COPROPRIETE ET TRANSMISSION DES PIECES AU CONSEIL SYNDICAL",
  "6.1. La fiche synthétique de la copropriété",
  "En application de l’article 8-2 de la loi du 10 juillet 1965, le syndic établit une fiche synthétique de la copropriété regroupant les données financières et techniques essentielles relatives à la copropriété et à son bâti, dont le contenu est défini par décret. Le syndic met à jour la fiche synthétique de la copropriété chaque année.\n\nLe syndic met cette fiche à disposition du copropriétaire qui en fait la demande dans le délai d'un mois. A défaut, il est tenu au paiement de la pénalité financière suivante : 15 € par jour de retard.\n\nCette pénalité est déduite de la rémunération forfaitaire annuelle du syndic lors de l'établissement des comptes à clôturer et à soumettre à l'assemblée générale.\n\nCes dispositions ne sont pas applicables aux syndics administrant des immeubles à destination totale autre que d'habitation.",
  "6.2. La transmission de pièces au conseil syndical",
  "En application du septième alinéa de l'article 21 de la loi 10 juillet 1965, le conseil syndical peut prendre connaissance et copie, à sa demande,",
  "Ne donnent lieu à aucune rémunération supplémentaire et sont comprises dans la rémunération forfaitaire : \n \n- les formalités de déclaration de sinistre concernant les parties communes et les parties privatives quand le sinistre a sa source dans les parties communes ; \n- la gestion des règlements aux bénéficiaires.",
  "7.1.2. Précisions concernant la tenue de l’assemblée générale annuelle",
  "Les parties conviennent que l’assemblée générale annuelle sera tenue pour une durée de [Coproprietes.DureeAG] heures à l’intérieur d’une plage horaire allant de 10 heures à 12h00 et de 14h00 à [Coproprietes.FinMaxAG] heures du Lundi au Vendredi, par le syndic ou un de ses préposés.",
  "7.1.3. Prestations optionnelles qui peuvent être incluses dans le forfait sur décision des parties",
  "Le forfait convenu entre les parties en vertu du présent contrat pourra expressément inclure l’une ou plusieurs des prestations suivantes:\nL’organisation de [Coproprietes.NbCS] réunion(s) avec le conseil syndical d’une durée de [Coproprietes.DureeCS] heure(s) à l’intérieur d’une plage horaire allant de 10 heures à 12h00 et de 14h00 à 18 heures du Lundi au Vendredi.",
  "7.1.4. Prestations qui peuvent être exclues des missions du syndic sur décision de l’assemblée générale des copropriétaires",
  "En application de l’article 18 de la loi du 10 juillet 1965, l’assemblée générale des copropriétaires peut, par décision spéciale prise aux conditions précisées par cet article : \n- dispenser le syndic d’offrir un accès en ligne sécurisé aux documents dématérialisés relatifs à la gestion de l’immeuble ou des lots gérés ;\n- confier les archives du syndicat des copropriétaires à une entreprise spécialisée aux frais du syndicat. \n \nEn cas de décision régulièrement adoptée par l’assemblée générale antérieurement à la conclusion du présent contrat, la prestation considérée n’est pas incluse dans le forfait.",
  "7.1.5. Modalités de rémunération",
  "La rémunération forfaitaire annuelle perçue par le syndic au titre du présent contrat s’élève à la somme de [HonoGestionHT] € hors taxes, soit [FormulaireContratSyndic.HonoGestion] € toutes taxes comprises plus frais postaux de [FormulaireContratSyndic.FraisPostaux] €. Cette rémunération est payable trimestriellement d’avance.\nLe forfait de frais postaux est réduit de 10 € pour chaque copropriétaire optant pour la lettre recommandée électronique et de 3 € pour chaque copropriétaire optant pour l’envoi des appels de fonds par mail. \n\nLes dépassements des horaires et durées convenus pour la tenue des assemblées générales, réunions et visites/vérifications périodiques incluses dans le forfait sont facturés selon le coût horaire mentionné au 7.2.1. L’envoi des documents afférents aux prestations du forfait ne donne pas lieu à remboursement au syndic des frais d’affranchissement ou d’acheminement engagés, au-delà du forfait indiqué ci-dessus.\n \nDans l’hypothèse où l’assemblée générale des copropriétaires a, en cours d’exécution du présent contrat et dans les conditions précisées à",
  "7.2.3. Prestations relatives au règlement de copropriété et à l’état descriptif de division",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["L’établissement ou la modification du règlement de copropriété à la suite d’une décision du syndicat prise en application de l’article 26 de la loi du 10 juillet 1965 (si l’assemblée générale décide, par un vote spécifique, de confier ces prestations au syndic)","Le montant des honoraires sera fixé lors de la décision de l’assemblée générale."],
  ["La publication de l’état descriptif de division et du règlement de copropriété ou des modifications apportées à ces actes","[ModifRCPHT] € HT soit [Tarifs.Tarif.ModifRCP] € TTC par lot principal."],
  "7.2.4. Prestations de gestion administrative et matérielle relatives aux sinistres",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["Les déplacements sur les lieux","[DepLieuHT] € HT soit [Tarifs.Tarif.DepLieu] € TTC"],
  ["La prise de mesures conservatoires","[MesConserHT] € HT soit [Tarifs.Tarif.MesConser] € TTC"],
  ["L'assistance aux mesures d’expertise","[AssExpHT] € HT soit [Tarifs.Tarif.AssExp] € TTC"],
  ["Suivi du dossier auprès de l’assureur","[DossierAssureurHT] € HT soit [Tarifs.Tarif.DossierAssureur] € TTC"],
  "Les prestations effectuées en dehors des jours et heures ouvrables et rendues nécessaires par l’urgence sont facturées au coût horaire majoré de 40%. Toute somme versée par l’assureur au syndic au titre de la couverture des diligences effectuées par ce dernier dans le cadre du règlement d’un sinistre vient en déduction de la rémunération due en application du présent article.",
  "7.2.5. Prestations relatives aux travaux et études techniques",
  "Les travaux dont la liste est fixée à l’article 44 du décret du 17 mars 1967 peuvent faire l’objet d’honoraires spécifiques.\n\nCes honoraires concernent : \n\n- les travaux de conservation ou d’entretien de l’immeuble, autres que ceux de maintenance ou d’entretien courant ;\n- les travaux portant sur les éléments d’équipement communs, autres que ceux de maintenance ;\n- les travaux d’amélioration, tels que la transformation d’un ou de plusieurs éléments d’équipement existants, l’adjonction d’éléments nouveaux, l’aménagement de locaux affectés à l’usage commun ou la création de tels locaux, l’affouillement du sol et la surélévation de bâtiments ;\n- les études techniques, telles que les diagnostics et consultations ;\n- d’une manière générale, les travaux qui ne concourent pas à la maintenance et à l’administration des parties communes ou à la maintenance et au fonctionnement des équipements communs de l’immeuble. \n\nLes honoraires complémentaires éventuels sont votés lors de la même assemblée générale que les travaux concernés et aux mêmes règles de majorité (article 18-1 A de la loi du 10 juillet 1965).",
  "7.2.7. Autres prestations (suite)",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["La constitution et le suivi du dossier d’emprunt souscrit au nom du syndicat en application du III de l’article 26-4 de la loi du 10 juillet 1965","62,50 € HT soit 75 € TTC par copropriétaire"],
  ["La gestion de l’emprunt souscrit au nom du syndicat en application du III de l’article 26-4 de la loi du 10 juillet 1965","29,17 € HT soit 35 € TTC par copropriétaire"],
  ["La constitution et le suivi d’un dossier de subvention accordé au syndicat","Tarif horaire indiqué au 7.2.1"],
  ["L’immatriculation initiale du syndicat","[ImmatInitialeHT] € HT soit [Tarifs.Tarif.ImmatInitiale] € TTC"],
  "8. FRAIS ET HONORAIRES IMPUTABLES AUX SEULS COPROPRIETAIRES",
  "Le coût des prestations suivantes est imputable au seul copropriétaire concerné.",
  "8.1. Frais de recouvrement (art. 10-1 a de la loi du 10 juillet 1965)",
  ["DÉTAIL DE LA PRESTATION","TARIFICATION PRATIQUÉE"],
  ["Mise en demeure par lettre recommandée avec accusé de réception","[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC"],
  ["Relance après mise en demeure","[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC"],
  ["Conclusion d’un protocole d’accord par acte sous seing privé","[EcheancierHT] € HT soit [Tarifs.Tarif.Echeancier] € TTC"],
  ["Frais de constitution d’hypothèque","[HypothequeHT] HT soit [Tarifs.Tarif.Hypotheque] € TTC"],
  ["Frais de main levée d’hypothèque","[HypothequeHT] HT soit [Tarifs.Tarif.Hypotheque] € TTC"],
  ["Dépôt d’une requête en injonction de payer","[InjonctionHT] € HT soit [Tarifs.Tarif.Injonction] € TTC"],
  ["Constitution du dossier transmis à l’auxiliaire de justice (uniquement en cas de diligences exceptionnelles)","[DossierJusticeHT] € HT soit [Tarifs.Tarif.DossierJustice] € TTC"],
  ["Suivi du dossier transmis à l’avocat (uniquement en cas de diligences exceptionnelles)","Tarif horaire indiqué au 7.2.1"],
  "8.2. Frais et honoraires liés aux mutations",
  ["DÉTAIL DE LA PRESTATION","TARIFICATION PRATIQUÉE"],
  ["Etablissement de l’état daté","[EtatDateHT] € HT soit [Tarifs.Tarif.EtatDate] € TTC"],
  ["Opposition sur mutation (article 20 I de la loi du 10 juillet 1965)","[OppositionHT] € HT soit [Tarifs.Tarif.Opposition] € TTC"],
  "8.3 Frais de délivrance des documents sur support papier (art. 33 du décret du 17 mars 1967 et R. 134-3 du code de la construction et de l’habitation)",
  ["DÉTAIL DE LA PRESTATION","TARIFICATION PRATIQUÉE"],
  ["Délivrance d’une copie du carnet d’entretien","[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC"],
  ["Délivrance d’une copie des diagnostics techniques","[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC"],
  "11. COMPETENCE",
  "Tous les litiges nés de l’exécution du présent contrat sont de la compétence de la juridiction du lieu de situation de l’immeuble.\n\nLes parties élisent domicile aux fins des présentes, aux adresses ci-dessous :\n \nPour le syndic : A l’adresse de son établissement.\n\nPour le syndicat : A l’adresse de son syndic.",
  "Fait en deux exemplaires et signé ce jour, le [DateAG] à \n\n\n\nMots nuls …\nLignes nulles …",
  "Le syndicat",
  "ANNEXE 1 AU CONTRAT DE SYNDIC\nLISTE NON LIMITATIVE DES PRESTATIONS INCLUSES DANS LE FORFAIT",
  ["PRESTATIONS","DÉTAILS"],
  ["I. - Assemblée générale","I-1° Préparation de l’assemblée générale.","a) Etablissement de l’ordre du jour  \nb) Mise à disposition de tous les copropriétaires des différentes pièces comptables et justificatives dans les conditions prévues à l’article 18-1 de la loi du 10 juillet 1965."],
  ["I. - Assemblée générale","I-2° Convocation à l’assemblée générale","Elaboration et envoi de la convocation avec l’ordre du jour, des documents à joindre à la convocation et des projets de résolutions."],
  ["I. - Assemblée générale","I-3° Tenue de l’assemblée générale.","a) Présence du syndic ou de son représentant à l’assemblée générale suivant les stipulations prévues par le contrat au titre du forfait ;\nb) Etablissement de la feuille de présence, émargement, vérification des voix et des pouvoirs ;\nc) Rédaction et tenue du registre des procès-verbaux."],
  ["PRESTATIONS","DÉTAILS"],
  ["IV. - Administration et gestion de la copropriété en conformité avec le règlement de copropriété","IV-12° Immatriculation du syndicat.","Mise à jour du registre d’immatriculation."],
  ["IV. - Administration et gestion de la copropriété en conformité avec le règlement de copropriété","IV-13° Documents obligatoires.","a) Elaboration et mise à jour de la fiche synthétique de copropriété ;\nb) Gestion de tous les audits, diagnostics et dossiers obligatoires (à l’exclusion du diagnostic de performance énergétique collectif et de l’audit énergétique, qui peuvent faire l’objet d’honoraires spécifiques dans les conditions précisées au 7.2.5 du présent contrat) ;\nc) Etablissement et mise à jour du carnet d’entretien conformément au décret n° 2001-477 du 30/05/2001 ;\nd) Etablissement et mise à jour de la liste des copropriétaires ;\ne) Notification de l’exercice du droit de délaissement prévue au III de l’article 18 de la loi du 10/07/1965."],
  ["IV. - Administration et gestion de la copropriété en conformité avec le règlement de copropriété","IV-14° Archives du syndicat et accès en ligne sécurisé aux documents dématérialisés.","a) Détention et conservation des archives, notamment les plans, le règlement de copropriété, l’état de répartition des charges, l’état de division, les procès-verbaux des assemblées générales, les diagnostics techniques, les contrats de travails des préposés du syndicat, les contrats d’assurance de l’immeuble et documents nécessaires pour leur mise en œuvre, les documents et décisions de justice relatifs à l’immeuble dont les délais de contestation ne sont pas révolus, les contrats d’entretien et de maintenance des équipements communs ainsi que toute pièce administrative (l’assemblée générale, statuant à la majorité de tous les copropriétaires, peut décider de confier les archives du syndicat des copropriétaires à une entreprise spécialisée aux frais du syndicat en application du I de l’article 18 de la loi du 10 juillet 1965) ;\nb) Transmission des archives au syndic successeur \nc) Elaboration et transmission au conseil syndical du bordereau récapitulatif des archives transmises au syndic successeur ;\nd) Mise à disposition d’un accès en ligne sécurisé aux documents dématérialisés relatifs à la gestion de l’immeuble ou des lots gérés (sauf décision contraire de l'assemblée générale"],
  ["PRESTATIONS","DÉTAILS"],
  "VI-24° Attestations et déclarations obligatoires.",
  "VI-25° Gestion des remplacements pendant les congés, arrêts maladie et maternité.",
  "VI-26° Mise en place et mise à jour du document unique d’évaluation des risques pour la santé et la sécurité des travailleurs.",
  "VI-27° Gestion de la formation du personnel du syndicat.",
  "VI-28° contrôle d’activité du personnel du syndicat.",
  "ANNEXE 2 AU CONTRAT DE SYNDIC\nModifié par décret n°2020-834 du 2 juillet 2020 – art. 51\nLISTE LIMITATIVE DES PRESTATIONS PARTICULIERES POUVANT DONNER LIEU AU VERSEMENT D’UNE REMUNERATION SPECIFIQUE COMPLEMENTAIRE",
  ["PRESTATIONS","DÉTAILS"],
  ["I. - Prestations relatives aux réunions et visites supplémentaires","1° Préparation, convocation et tenue d'assemblées générales supplémentaires et dépassement des plages horaires de référence convenues ;\n2° Organisation de réunions supplémentaires avec le conseil syndical ;\n3° Réalisation de visites supplémentaires de la copropriété."],
  ["II. - Prestations relatives au règlement de copropriété et à l'état descriptif de division :","4° Etablissement ou modification du règlement de copropriété à la suite d'une décision du syndicat ;\n5° Publication de l'état descriptif de division et du règlement de copropriété ou des modifications apportées à ces actes."],
  ["III. - Prestations de gestion administrative et matérielle relatives aux sinistres","6° Déplacements sur les lieux ;\n7° Prise de mesures conservatoires ;\n8° Assistance aux mesures d'expertise ;\n9° Suivi du dossier auprès de l'assureur."],
  "IV. - Prestations relatives aux travaux et études techniques dont la liste est fixée à l'article 44 du décret du 17 mars 1967 pris pour l'application de la loi du 10 juillet 1965.",
  ["V. - Prestations relatives aux litiges et contentieux (hors recouvrement de créances des copropriétaires)","10° Mise en demeure par lettre recommandée accusée de réception ;\n11° Constitution du dossier transmis à l'avocat, à l'huissier, à l'assureur protection juridique ;\n12° Suivi du dossier transmis à l'avocat."],
  ["VI. - Autres prestations","13° Diligences spécifiquement liées à la préparation des décisions d'acquisition ou de dispositions de parties communes (hors prestations visées au II) ;\n14° Reprise de la comptabilité sur exercice(s) antérieur(s) non approuvés ou non réparti(s), en cas de changement de syndic ;\n15° Représentation du syndicat aux assemblées d'une structure extérieure (syndicat secondaire, union de syndicats, association syndicale libre) créée en cours de mandat ainsi qu'aux assemblées supplémentaires"],
  "FICHE D'INFORMATION SUR LES PRIX ET LES PRESTATIONS PROPOSÉES",
  "1. Informations générales",
  ["Identification du syndic","Nom : REAL 31 \nDénomination sociale : REAL 31\nImmatriculation au registre du commerce et des sociétés de Versailles\nN° d'identification : 479 696 767\nTitulaire de la carte professionnelle, n° CPI 7801 2016 000 014 479, délivrée le 25 Novembre 2025 par CCI Paris Ile de France  \nAdresse du siège social : 31 rue du Prieuré - 78600 Maisons-Laffitte"],
  ["Identification de la copropriété concernée, telle que résultant du registre institué à l'article L. 711-1 du code de la construction et de l'habitation","Adresse : [Coproprietes.Adresse1] [Coproprietes.Adresse2] [Coproprietes.Adresse3] [Coproprietes.CP] [Coproprietes.Ville]\nN° d'immatriculation : [Coproprietes.RegistreNumero]\nNombre de lots de la copropriété :\n- Lots à usage de logements, de bureaux ou de commerces : [Coproprietes.NbLot]\n- Autres lots : [Coproprietes.NbAutreLot]"],
  ["Durée du contrat","Le contrat est proposé pour une durée \nde [DureeContrat]."],
  ["Quotité des heures ouvrables","Les jours et heures de référence pour la détermination des modalités de rémunération sont fixés comme suit :\nDu lundi au vendredi  de 9h30 à 12h30 et de 14h à 18h et le samedi de 09h30 à 12h30 et de 14h00 à 16h00\nSauf  les jours fériés"],
  ["Horaires de disponibilité","Les jours et horaires de disponibilité du syndic sauf urgences (accueil physique et/ou téléphonique) pour les démarches individuelles de chaque copropriétaire ou occupant de l'immeuble sont fixés comme suit :\nAccueil physique et téléphonique : \nDu lundi au vendredi de 9h30 à 12h30 et de 14h à 18h et le samedi de 09h30 à 12h30 et de 14h00 à 16h00"],
  "2. Forfait",
  "Le forfait comprend toutes les prestations fournies par le syndic au titre de sa mission, à l'exclusion des prestations limitativement énumérées à l'annexe 2 du décret n° 67-223 du 17 mars 1967.",
  "La rémunération forfaitaire du syndic pour 12 mois proposée s'élève à la somme de :",
  "[HonoGestionHT] € HT, soit [FormulaireContratSyndic.HonoGestion] € TTC.",
  "Il est prévu une révision du montant forfaitaire à l'issue de cette période de 12 mois : NON",
  "Tarif forfaitaire total proposé",
  ["Organisation d'une réunion supplémentaire avec le conseil syndical d'une durée de 1 heure.","[Tarifs.Tarif.CsSupp] € TTC"],
  ["Réalisation d'une visite supplémentaire de la copropriété","[Tarifs.Tarif.VisiteSupp] € TTC"],
  "3.2. Prestations de gestion administrative et matérielle relatives aux sinistres",
  "Tarif forfaitaire total proposé",
  ["Déplacements sur les lieux","[Tarifs.Tarif.DepLieu] € TTC"],
  ["Prise de mesures conservatoires","[Tarifs.Tarif.MesConser] € TTC"],
  ["Assistance aux mesures d'expertise","[Tarifs.Tarif.AssExp] € TTC"],
  ["Suivi du dossier auprès de l'assureur","[Tarifs.Tarif.DossierAssureur] € TTC"],
  "Le cas échéant, le taux majoré unique pour des prestations effectuées en dehors des jours et heures ouvrables et rendues nécessaires par l'urgence est fixé à 100 % du coût horaire TTC prévu au point 3.",
  "3.3. Prestations relatives aux travaux et aux études techniques",
  "Les travaux mentionnés à l'article 44 du décret du 17 mars 1967 peuvent faire l'objet d'honoraires spécifiques complémentaires, qui sont votés avec les travaux en assemblée générale, aux mêmes règles de majorité (III de l'article 18-1 A de la loi du 10 juillet 1965).",
  "3.4. Prestations relatives aux litiges et aux contentieux (hors frais de recouvrement)",
  ["Au temps passé","Tarif forfaitaire total proposé"],
  ["Mise en demeure d'un tiers par lettre recommandée avec accusé de réception","[Tarifs.Tarif.MED] € TTC"],
  ["Constitution du dossier transmis à l'avocat, à l'huissier de justice ou à l'assureur « protection juridique »","[Tarifs.Tarif.DossierAvocat] € TTC"],
  ["Suivi du dossier transmis à l'avocat","Tarif horaire indiqué au 3"],
  "4. Tarification pratiquée pour les principales prestations imputables au seul copropriétaire concerné",
  "• Frais de recouvrement\n-Mise en demeure par lettre recommandée avec accusé de \nréception : [Tarifs.Tarif.MED] € TTC\n-Relance après mise en demeure : [Tarifs.Tarif.MED] € TTC\n\n• Frais et honoraires liés aux mutations\n-Etablissement de l'état daté : [Tarifs.Tarif.EtatDate] € TTC\n-Opposition sur mutation : [Tarifs.Tarif.Opposition] € TTC\n\n• Préparation, convocation et tenue d'une assemblée générale à la demande d'un ou plusieurs copropriétaires, pour des questions concernant leurs droits ou obligations\n-Etablissement de l'ordre du jour et envoi de la convocation, présence du syndic ou de son représentant à l'assemblée générale, rédaction et tenue du registre des procès-verbaux, envoi et notification du procès-verbal comportant les décisions prises en assemblée générale des copropriétaires : [Tarifs.Tarif.AGE] € TTC / lot principal",
] as const;

/** Colonne de droite du contrat, de haut en bas. */
export const GABARIT_DROITE: readonly BlocGabarit[] = [
  "PRÉAMBULE",
  "Le présent contrat de mandat est soumis aux dispositions de la loi du 10 juillet 1965 précitée et des textes pris pour son application, notamment le décret du 17 mars 1967. Les articles 1984 et suivants du Code civil s’y appliquent de façon supplétive.\n \nLe syndic professionnel est soumis aux dispositions de la loi du 2 janvier 1970, ci-dessus mentionnée, et au décret n° 72-678 du 20 juillet 1972 pris pour son application ainsi qu’au code de déontologie promulgué en application de l’article 13-1 de cette même loi.\n\nLe syndic professionnel ne peut ni demander ni recevoir, directement ou indirectement, d’autres rémunérations, à l’occasion de la mission dont il est chargé au titre du présent contrat, que celles dont les conditions de détermination y sont précisées, y compris en provenance de tiers (article 66 du décret du 20 juillet 1972 précité).",
  "1. MISSIONS",
  "Le syndicat confie au syndic qui l’accepte mandat d’exercer la mission de syndic de l’immeuble ci dessus désigné. L’objet de cette mission est notamment défini à l’article 18 de la loi du 10 juillet 1965 précitée et par le présent contrat.",
  "2. DUREE DU CONTRAT",
  "Le présent contrat est conclu pour une durée de [DureeContrat].\n\nIl prendra effet le [DebutContrat] et prendra fin le [FinContrat].\n\nIl ne peut être conclu un nouveau contrat que par décision expresse de l’assemblée générale.",
  "3. RESILIATION DU CONTRAT A L'INITIATIVE DU CONSEIL SYNDICAL",
  "Le contrat de syndic peut être résilié, à l'initiative du conseil syndical, par décision de l'assemblée générale des copropriétaires statuant à la majorité des voix de tous les copropriétaires (art. 25 de la loi du 10 juillet 1965).\n\nCette résiliation du contrat doit être fondée sur une inexécution suffisamment grave reprochée au syndic. Le conseil syndical notifie au syndic une demande motivée d'inscription de la question à l'ordre du jour de la prochaine assemblée générale, en précisant la ou les inexécutions qui lui sont reprochées.\n\nLa résiliation prend effet à la date déterminée par l'assemblée générale et au plus tôt un jour franc après la tenue de celle-ci.",
  "après en avoir donné avis au syndic, de toutes pièces ou documents, correspondances ou registres se rapportant à la gestion du syndic et, d'une manière générale, à l'administration de la copropriété.\n\nEn l'absence de transmission desdites pièces, au-delà du délai d'un mois à compter de la demande du conseil syndical, le syndic est tenu au paiement de la pénalité suivante : 15 € par jour de retard.\n\nCette pénalité est déduite de la rémunération forfaitaire annuelle du syndic lors de l'établissement des comptes définitifs à clôturer et à soumettre à l'assemblée générale.",
  "7. PRESTATIONS ET MODALITES DE REMUNERATION DU SYNDIC PROFESSIONNEL",
  "Les jours et heures ouvrables de référence pour la détermination des modalités de rémunération sont fixés comme suit :\n \nDu lundi au vendredi de 9h30 à 12h30 et de 14h00 à 18h00\nLe samedi de 9h30 à 12h30 et de 14h à 16h.\n\nSauf en cas d’urgence, les démarches individuelles de chaque copropriétaire ou occupant de l’immeuble auprès du syndic s’effectuent aux jours et heures suivantes (accueil physique et/ou téléphonique effectif) :\n \nAccueil physique :\nDu lundi au Vendredi de 9h30 à 12h30 et de 14h00 à 18h00;\nLe samedi de 9h30 à 12h30 et de 14h à 16h. \n\nAccueil téléphonique :\nDu lundi au Vendredi de 9h30 à 12h30 et de 14h00 à 18h00;\nLe samedi de 9h30 à 12h30 et de 14h à 16h.\n\nLa rémunération du syndic professionnel est déterminée de manière forfaitaire. Toutefois, une rémunération spécifique peut être perçue en contrepartie des prestations particulières limitativement énumérées à l’annexe 2 du décret du 17 mars 1967 et dans les conditions stipulées au 7.2 du présent contrat (art. 18 1 A de la loi du 10 juillet 1965).",
  "7.1. LE FORFAIT",
  "7.1.1. Contenu du forfait",
  "Le forfait convenu entre les parties comprend toutes les prestations fournies par le syndic au titre de sa mission, à l’exclusion des prestations limitativement énumérées à l’annexe 2 du décret du 17 mars 1967. A ce titre, il effectue les visites et vérifications périodiques de la copropriété impliquées par la mission relative à l’administration, à la conservation, à la garde et à l’entretien de l’immeuble. Il est convenu la réalisation, au minimum, de :\n\n[Coproprietes.NbVisite] visite(s) et vérification(s) périodique(s) de la copropriété, sur demande du conseil syndical, d’une durée de 1 heure minimum, avec rédaction d’un rapport une fois par an et en présence du président du conseil syndical si celui-ci le souhaite. \n\nUne liste non limitative des prestations incluses dans le forfait est annexée au présent contrat. \n\nLes frais de reprographie, les frais d’affranchissement et les frais administratifs afférents aux prestations du forfait sont inclus dans la rémunération forfaitaire.",
  "l’article 18 de la loi du 10 juillet 1965, décidé de confier les archives du syndicat à une entreprise spécialisée, le montant de sa rémunération forfaitaire annuelle hors taxes est imputé de la somme toutes taxes comprises effectivement facturée au syndicat par le tiers auquel cette tâche aura été confiée (sur justificatif).\n\nDans l’hypothèse où l’assemblée générale des copropriétaires a, en cours d’exécution du présent contrat et dans les conditions précisées à l’article 18 de la loi du 10 juillet 1965, décidé de dispenser le syndic de son obligation de mise à disposition d’un service d’accès en ligne aux documents dématérialisés, le montant de sa rémunération forfaitaire annuelle est imputé de la somme de 0€ (que les parties conviennent de fixer dès à présent) \n\nLe montant de l’imputation prévue au titre des deux derniers alinéas est calculé prorata temporis de la période restant à courir jusqu’à la date d’exigibilité de la rémunération.",
  "7.2. LES PRESTATIONS PARTICULIERES POUVANT DONNER LIEU A REMUNERATION COMPLEMENTAIRE",
  "7.2.1. Modalités de rémunération des prestations particulières",
  "La rémunération due au syndic professionnel au titre des prestations particulières, à l'exception de celles citées au 7.2.5, est calculée pour chacune d’elles : \n - soit en application du seul coût horaire ci-dessous, appliqué au prorata du temps passé : \n[TauxHoraireHT] € HT/ heure, soit [Tarifs.Tarif.TauxHoraire] € TTC / heure. La facturation se fait à la demi-heure. Toute demi-heure commencée étant due. \n- soit en application du tarif forfaitaire total convenu par les parties, exprimé hors taxes et toutes taxes comprises, pour chaque prestation particulière. \n \nLa rémunération due au titre des prestations particulières s’entend frais d’envoi compris. L’envoi des documents afférents aux prestations particulières ne donne lieu à aucun remboursement au syndic des frais d’affranchissement ou d’acheminement engagés qui sont inclus dans la rémunération forfaitaire.",
  "7.2.2. Prestations relatives aux réunions et visites supplémentaires \n(au-delà du contenu du forfait stipulé aux 7.1.1 et 7.1.3)",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["La préparation, la convocation et la tenue d’une assemblée générale supplémentaire de 2 heures, à l’intérieur d’une plage horaire allant de 10 heures à  20 heures","[AGEHT] € HT soit [Tarifs.Tarif.AGE] € TTC par lot principal. Le cas échéant, majoration spécifique unique pour dépassement d’horaires convenus : 100%"],
  ["L’organisation d’une réunion supplémentaire avec le conseil syndical d’une durée de 1 heure, par rapport à celle incluse dans le forfait au titre du 7.1.3","[CsSuppHT] € HT soit [Tarifs.Tarif.CsSupp] € TTC. Tout dépassement d’horaire sera facturé suivant tarif énoncé au 7.2.1."],
  ["La réalisation d’une visite supplémentaire de la copropriété d’une durée de 1 heure, avec rédaction d’un rapport, en présence du président du conseil syndical (par rapport à celles incluses dans le forfait au titre du 7.1.1)","[VisiteSuppHT] € HT soit [Tarifs.Tarif.VisiteSupp] € TTC. Tout dépassement d’horaire sera facturé suivant tarif énoncé au 7.2.1."],
  "Le présent contrat ne peut se lire comme fixant un barème relatif à ces honoraires spécifiques, même à titre indicatif.\n \nUne telle rémunération fixée dans le projet de résolution soumis au vote de l’assemblée générale doit être exprimée hors taxes et toutes taxes comprises, en application du pourcentage du montant hors taxes des travaux, à un taux dégressif selon l’importance des travaux préalablement à leur exécution.\n \nLe choix du prestataire par l’assemblée générale est précédé d’une mise en concurrence dans les conditions prévues au deuxième alinéa de l’article 21 de la loi du 10 juillet 1965 et à l’article 19 2 du décret du 17 mars 1967.\n \nLes diligences entreprises par le syndic dans le cadre de la réalisation du diagnostic de performance énergétique collectif et de l’audit énergétique peuvent donner lieu à rémunération dans les conditions prévues au présent article.",
  "7.2.6. Prestations relatives aux litiges et contentieux \n(hors frais de recouvrement visés au point 8.1)",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["La mise en demeure d’un tiers par lettre recommandée avec accusé de réception","[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC"],
  ["La constitution du dossier transmis à l’avocat, à l’huissier de justice ou à l’assureur protection juridique (à l’exclusion des formalités visées au 7.2.4)","[DossierAvocatHT] € HT soit [Tarifs.Tarif.DossierAvocat] € TTC"],
  ["Le suivi du dossier transmis à l’avocat","Tarif horaire indiqué au 7.2.1"],
  "7.2.7. Autres prestations",
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["Les diligences spécifiquement liées à la préparation des décisions d’acquisition ou de disposition des parties communes","Le montant des honoraires sera fixé lors de la décision de l’assemblée générale confiant au syndic les prestations concernées"],
  ["La reprise de la comptabilité sur exercice(s) antérieur(s) non approuvés ou non répartis (changement de syndic)","[RepriseComptaHT] € HT soit [Tarifs.Tarif.RepriseCompta] € TTC par lot principal."],
  ["La représentation du syndicat aux assemblées d’une structure extérieure (syndicat secondaire, union de syndicats, association syndicale libre) créée en cours de mandat ainsi qu’aux assemblées supplémentaires de ces mêmes structures si elles existaient antérieurement à la signature du présent contrat","Tarif horaire indiqué au 7.2.1"],
  ["La constitution et le suivi du dossier d’emprunt souscrit au nom du syndicat en application de l’article 26-4 alinéa 1 et 2 de la loi du 10 juillet 1965","[DossierEmpruntHT] € HT soit [Tarifs.Tarif.DossierEmprunt] € TTC par copropriétaire"],
  ["DETAIL DE LA PRESTATION","MODALITE DE TARIFICATION\nconvenues"],
  ["Délivrance des informations utiles à la réalisation d’un diagnostic de performance énergétique individuel mentionnées à l’art. R. 134-3 du code de construction et habitation.","[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC"],
  ["Délivrance au copropriétaire d’une copie certifiée conforme ou d’un extrait de procès-verbal d’assemblée générale ainsi que des copies et annexes (hors notification effectuée en application de l’article 18 du décret du 17 mars 1967).","[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC"],
  "8.4 Préparation, convocation et tenue d’une assemblée générale à la demande d’un ou plusieurs copropriétaires, pour des questions concernant leurs droits ou obligations (art. 17-1 AA de la loi du 10 juillet 1965)",
  ["DÉTAIL DE LA PRESTATION","TARIFICATION PRATIQUÉE"],
  ["Etablissement de l’ordre du jour ; élaboration et envoi de la convocation avec l’ordre du jour, des documents à joindre à la convocation et des projets de résolutions ; présence du syndic ou de son représentant à l’assemblée générale ; établissement de la feuille de présence ; émargement, vérification des voix et des pouvoirs ; rédaction et tenue du registre des procès- verbaux ; envoi et notification du procès-verbal comportant les décisions prises en assemblée des copropriétaires (opposant ou défaillant) et, le cas échéant, information des occupants de chaque immeuble de la copropriété des décision prises par l’assemblée générale par affichage d’un procès-verbal abrégé dans les parties communes (art. 44 de la loi n° 86-1290 du 23/12/1986).","[AGEHT] € HT soit [Tarifs.Tarif.AGE] € TTC \npar lot principal. Le cas échéant, majoration spécifique unique pour dépassement d’horaires convenus : 100%"],
  "9. COPROPRIETE EN DIFFICULTE",
  "En application de l’article 29 1 de la loi du 10 juillet 1965 fixant le statut de la copropriété des immeubles bâtis, la désignation d’un administrateur provisoire entraîne la cessation de plein droit sans indemnité du présent contrat.",
  "10. REDDITION DE COMPTE",
  "La reddition de compte interviendra chaque année à la date ou selon la périodicité suivante : dans les 6 mois qui suivent la clôture de l’exercice. La répartition individuelle (régularisation des charges) sur le compte de chaque copropriétaire interviendra chaque année dans les deux mois suivant l’Assemblée Générale statuant sur les comptes de l’exercice écoulé.",
  ["PRESTATIONS","DÉTAILS"],
  ["II. - Conseil syndical","II-5° Mise à disposition et communication au conseil syndical de toutes pièces ou documents se rapportant à la gestion du syndicat ou des lots gérés (notamment par accès en ligne sécurisé)"],
  ["II. - Conseil syndical","II-6° Recueil des avis écrits du conseil syndical lorsque sa consultation est obligatoire."],
  ["III. - Gestion des opérations financières et comptabilité générale de la copropriété","III-7° Comptabilité du syndicat.","a) Etablissement des comptes de gestion et des annexes du syndicat des copropriétaires, conformément à l’article 14-3 de la loi du 10 juillet 1965 ; \nb) Etablissement du budget prévisionnel, en collaboration avec le conseil syndical, conformément à l’article 14-1 de la même loi et au décret n° 2005-240 du 14 mars 2005 ;\nc) Présentation des comptes en conformité avec la réglementation en vigueur."],
  ["III. - Gestion des opérations financières et comptabilité générale de la copropriété","III-8° Comptes bancaires.","a) Ouverture d’un compte bancaire séparé ;\nb) Ouverture d’un compte bancaire séparé destiné à recevoir les cotisations prévues à l’article 14-2 de la loi du 10 juillet 1965."],
  ["III. - Gestion des opérations financières et comptabilité générale de la copropriété","III-9° Comptabilité séparée de chaque copropriétaire.","a) Tenue des comptes de chaque copropriétaire ; \nb) Appel des provisions sur budget prévisionnel ;\n c) Imputations des consommations individuelles de fluide ou d’énergie ; \nd) Reconstitution des consommations, forfaits et régularisations sur compteurs en l’absence de relevé ; \ne) Appels sur régularisations de charge ; \nf) Appels des cotisations du fonds de travaux."],
  ["III. - Gestion des opérations financières et comptabilité générale de la copropriété","III-10° Autres.","a) Vérification et paiement des factures des fournisseurs et prestataires ;\nb) Recouvrement des créances auprès des tiers : relance par lettre simple avant mise en demeure ;\nc) Calcul des intérêts légaux au profit du syndicat ; \nd) Attestation de TVA aux fournisseurs et prestataires."],
  ["III. - Gestion des opérations financières et comptabilité générale de la copropriété","III-11° Remise au syndic successeur.","Remise de l’état financier, des références des comptes bancaires du syndicat, des coordonnées de la banque, de l’état des comptes des copropriétaires et des comptes du syndicat."],
  ["PRESTATIONS","DÉTAILS"],
  "des copropriétaires statuant dans les conditions prévues à l’article 18 de la loi du 10 juillet 1965).",
  ["IV-15° Entretien courant et maintenance.","a) Visites de la copropriété et vérifications, selon les stipulations prévues au contrat ;\nb) Gestion des travaux d’entretien courant et de maintenance visés à l’article 45 du décret du 17 mars 1967 ;\nc) Vérifications périodiques imposées par les réglementations en vigueur sur les éléments d’équipement communs ;\nd) Négociation, passation, suivi des marchés des prestataires et gestion des contrats à l’échéance dans le cadre du budget prévisionnel ;\ne) Etablissement et présentation à l’assemblée générale, au moins tous les trois ans, de la liste des travaux d’entretien et de conservation des parties communes et des éléments d’équipement commun nécessaires dans les trois années à échoir, en vue de la constitution de provisions spéciales;\nf) En vue de la consultation au cours d’une assemblée générale incluse dans le forfait, appel d’offres, étude des devis et mise en concurrence résultant de la demande d’une pluralité de devis ou de l’établissement d’un devis descriptif soumis à l’évaluation de plusieurs entreprises lorsque celle-ci est obligatoire dans le cadre des travaux de maintenance définis à l’article 45 du décret du 17 mars 1967."],
  ["V. - Assurances","V-16° Souscription des polices d’assurance au nom du syndicat soumise au vote de l’assemblée générale."],
  ["V. - Assurances","V-17° Déclaration des sinistres concernant les parties communes ou les parties privatives lorsque le dommage a sa source dans les parties communes."],
  ["V. - Assurances","V-18° Règlement des indemnités aux bénéficiaires."],
  ["VI. - Gestion du personnel","VI-19° Recherche et entretien préalable."],
  ["VI. - Gestion du personnel","VI-20° Etablissement du contrat de travail et de ses avenants éventuels."],
  ["VI. - Gestion du personnel","VI-21° Gestion des procédures de rupture du contrat de travail."],
  ["VI. - Gestion du personnel","VI-22° Paiement du salaire, tenue du livre des salaires, édition des bulletins de paies."],
  ["VI. - Gestion du personnel","VI-23° Déclarations et paiement aux organismes fiscaux et sociaux."],
  ["PRESTATIONS","DÉTAILS"],
  "de ces mêmes structures si elles existaient antérieurement à la signature du contrat de syndic ;\n16° Constitution et suivi du dossier d'emprunt souscrit au nom du syndicat en application des alinéas 1 et 2 de l'article 26-4 de la loi du 10 juillet 1965 ; \n16°bis Constitution et suivi du dossier d’emprunt souscrit au nom du syndicat en application du III de l’article 26-4 de la loi du 10 juillet 1965 et gestion de cet emprunt ;\n17° Constitution et suivi d'un dossier de subvention au profit du syndicat ;\n18° Immatriculation initiale du syndicat ;\n19° Opérations de liquidation en cas de disparition de plein droit de la copropriété et de dissolution du syndicat des copropriétaires par réunion de tous les lots entre les mains d'un même copropriétaire, en application du dernier alinéa de l'article 46-1 de la loi du 10 juillet 1965.",
  "NOTA : Conformément au IV de l’article 53 du décret n° 2020-834 du 2 juillet 2020, ces dispositions s'appliquent aux contrats de syndic conclus postérieurement au 4 juillet 2020.",
  "2.1. Prestations obligatoirement incluses dans le forfait du syndic",
  ["Visites et vérifications\nde la copropriété","Au titre de sa mission d'administration, de conservation, de garde et d'entretien de l'immeuble, le syndic s'engage à effectuer, sur demande du conseil syndical, au minimum le nombre annuel de visite(s) suivant :[Coproprietes.NbVisite]\nCe(s) visite(s) auront une durée minimum de : 1 heure\nLe Président du conseil syndical sera invité à ces réunion(s) : Oui\nCes réunions donneront lieu à la rédaction d'un rapport : Oui"],
  ["Tenue de l'assemblée générale annuelle","L'assemblée générale annuelle, qui débutera à l'heure de la convocation, aura une durée de : [Coproprietes.DureeAG] heure(s)\nL'assemblée générale se tiendra à l'intérieur d'une plage horaire allant de 10 heures à 12 heures et de 14 heures à [Coproprietes.FinMaxAG] heures."],
  "2.2. Prestations optionnelles pouvant être incluses dans le forfait sur décision des parties",
  ["Tenue d'assemblées générales autres que l'assemblée générale annuelle (1)","La préparation, la convocation et la tenue d’assemblée (s) générale (s) d’une durée de 2 heures, à l'intérieur d'une plage horaire allant de 10h à 12h et de 14h  à 20h.","Non inclus : \n[Tarifs.Tarif.AGE] € / lot principal"],
  ["Réunions avec le conseil syndical","L'organisation de [Coproprietes.NbCS] réunion(s) avec le conseil syndical d'une durée de [Coproprietes.DureeCS] heure(s), à l'intérieur d'une plage horaire allant de 10 heures à 18 heures.","Inclus"],
  "(1) Autres que celles à la demande d'un ou plusieurs copropriétaires, pour des questions concernant leurs droits ou obligations, qui sont mentionnées au point 4.",
  "Le cas échéant, les dépassements d'horaires ou de la durée convenus pour les prestations des 2.1 et 2.2 seront facturés selon le seul coût horaire suivant (coût horaire prévu au point 3) : [TauxHoraireHT] € HT/ heure, soit [Tarifs.Tarif.TauxHoraire] € TTC / heure.",
  "3. Prestations particulières non comprises dans le forfait",
  "La rémunération du syndic pour chaque prestation particulière pouvant donner lieu au versement d'une rémunération spécifique complémentaire s'effectue, pour chacune de ces prestations, au choix :\n- Coût horaire unique : [TauxHoraireHT] € HT/ heure, soit [Tarifs.Tarif.TauxHoraire] € TTC / heure.\n- Au tarif forfaitaire total proposé",
  "3.1. Prestations relatives aux réunions et visites supplémentaires",
  "Tarif forfaitaire",
  ["Préparation, convocation et tenue d'une assemblée générale supplémentaire d'une durée de 2 heures, à l'intérieur d'une plage horaire allant de 10 heures à 20 heures. Le cas échéant, le taux majoré unique pour dépassement de la plage horaire ou de la durée convenue est fixé à 100 % du coût horaire TTC prévu au point 3.","[Tarifs.Tarif.AGE] € TTC / lot principal"],
  "(Les conditions de mise en œuvre de cette dernière prestation sont prévues à l'article 8-1 du décret n° 67-223 du 17 mars 1967)",
] as const;

/** Les placeholders presents dans le gabarit, pour verifier qu'on sait tous les remplir. */
export const PLACEHOLDERS_GABARIT: readonly string[] = [
  "[AGEHT]",
  "[AssExpHT]",
  "[Coproprietes.Adresse1]",
  "[Coproprietes.Adresse2]",
  "[Coproprietes.Adresse3]",
  "[Coproprietes.Agence]",
  "[Coproprietes.Assurance]",
  "[Coproprietes.CP]",
  "[Coproprietes.DateAssurance]",
  "[Coproprietes.DureeAG]",
  "[Coproprietes.DureeCS]",
  "[Coproprietes.FinMaxAG]",
  "[Coproprietes.NbAutreLot]",
  "[Coproprietes.NbCS]",
  "[Coproprietes.NbLot]",
  "[Coproprietes.NbVisite]",
  "[Coproprietes.RegistreNumero]",
  "[Coproprietes.Ville]",
  "[CsSuppHT]",
  "[DateAG]",
  "[DebutContrat]",
  "[DelivranceCopieHT]",
  "[DepLieuHT]",
  "[DossierAssureurHT]",
  "[DossierAvocatHT]",
  "[DossierEmpruntHT]",
  "[DossierJusticeHT]",
  "[DureeContrat]",
  "[EcheancierHT]",
  "[EtatDateHT]",
  "[FinContrat]",
  "[FormulaireContratSyndic.FraisPostaux]",
  "[FormulaireContratSyndic.HonoGestion]",
  "[HonoGestionHT]",
  "[HypothequeHT]",
  "[ImmatInitialeHT]",
  "[InjonctionHT]",
  "[MEDHT]",
  "[MesConserHT]",
  "[ModifRCPHT]",
  "[OppositionHT]",
  "[RepriseComptaHT]",
  "[Tarifs.Tarif.AGE]",
  "[Tarifs.Tarif.AssExp]",
  "[Tarifs.Tarif.CsSupp]",
  "[Tarifs.Tarif.DelivranceCopie]",
  "[Tarifs.Tarif.DepLieu]",
  "[Tarifs.Tarif.DossierAssureur]",
  "[Tarifs.Tarif.DossierAvocat]",
  "[Tarifs.Tarif.DossierEmprunt]",
  "[Tarifs.Tarif.DossierJustice]",
  "[Tarifs.Tarif.Echeancier]",
  "[Tarifs.Tarif.EtatDate]",
  "[Tarifs.Tarif.Hypotheque]",
  "[Tarifs.Tarif.ImmatInitiale]",
  "[Tarifs.Tarif.Injonction]",
  "[Tarifs.Tarif.MED]",
  "[Tarifs.Tarif.MesConser]",
  "[Tarifs.Tarif.ModifRCP]",
  "[Tarifs.Tarif.Opposition]",
  "[Tarifs.Tarif.RepriseCompta]",
  "[Tarifs.Tarif.TauxHoraire]",
  "[Tarifs.Tarif.VisiteSupp]",
  "[TauxHoraireHT]",
  "[VisiteSuppHT]",
] as const;
