// Gabarit du contrat de mandat du gestionnaire d'une ASL / AFUL - GENERE, NE PAS EDITER A LA MAIN.
//
// Produit par `node scripts/convertir-gabarit-mandat.mjs` a partir du modele Word du cabinet
// « CONTRAT DE MANDAT DU GESTIONNAIRE PROFESSIONNEL.docx » (docs/). Meme format que
// gabarit-contrat.ts, mais UNE colonne de 12 cases : un bloc est un paragraphe (chaine) ou
// une ligne de tableau (cellules avec leur largeur en cases). Placeholders `[Xxx]` resolus a
// l'affichage, les memes que le contrat de syndic, plus [FormeJuridique] et
// [Coproprietes.Denomination].
//
// 133 blocs (dont 28 lignes de tableau), 53 placeholders distincts.

import type { BlocGabarit } from "./gabarit-contrat";

/** Le nombre de cases de la colonne unique : l'unite des largeurs. */
export const CASES_MANDAT = 12;

/** Le titre, sur deux lignes. */
export const TITRE_MANDAT = "CONTRAT DE MANDAT DU GESTIONNAIRE PROFESSIONNEL\nD’UNE [FormeJuridique] N°";

/** Le contrat, de haut en bas, sur une colonne. */
export const GABARIT_MANDAT: readonly BlocGabarit[] = [
  "le present contrat de mandat est conclu entre :",
  "1. D’une part :",
  "L’[FormeJuridique] de l’ensemble immobilier sise à l’adresse suivante : [Coproprietes.Adresse1] [Coproprietes.Adresse2] [Coproprietes.Adresse3] – [Coproprietes.CP] [Coproprietes.Ville]",
  "Ci-après dénommé l’[FormeJuridique] [Coproprietes.Denomination]",
  "et",
  "2. D’autre part :",
  "La SAS REAL 31",
  "[Coproprietes.Agence],",
  "ayant son siège social à l’adresse suivante :",
  "31 rue du Prieuré",
  "78600  Maisons-Laffitte,",
  "immatriculée au registre du commerce et des sociétés de Versailles sous le n° 479 696 767, représentée par Emmanuel LOPES en sa qualité de Dirigeant.",
  "Titulaire de la carte professionnelle n° CPI 7801 2016 000 014 479, permettant l’exercice de l’activité de : transaction sur immeubles et fonds de commerces * gestion immobilière * Syndic de copropriété, délivrée par la CCI Paris Île-de-France. Garanti par GALIAN-SMABTP, 89 rue la Boétie – 75008 Paris sous la référence 110891J, contrat souscrit le 13/12/2004 et couvrant la zone géographique suivante : République Française (France Métropolitaine, DROM-COM).",
  "Assuré(e) en responsabilité civile professionnelle par MMA IARD – 14 boulevard Marie et Alexandre Oyon – 72030 Le Mans Cedex 9 sous le contrat n° 127 103 751 souscrit le 13/12/2004, couvrant la zone géographique suivante : République Française (France Métropolitaine, DROM-COM).",
  "Adhérent à la Fédération Nationale de l’Immobilier (FNAIM), ayant le titre professionnel de Dirigeant obtenu en France et visé ci-dessus",
  "Numéro individuel d’identification à la TVA FR : FR59 479 696 767",
  "Intermédiaire immatriculé à l’ORIAS sous le numéro 15000214",
  "Ci-après dénommé le gestionnaire ;",
  "PRÉAMBULE",
  "Le présent contrat n’est pas soumis aux dispositions de la loi du 10 juillet 1965 précitée et des textes pris pour son application, notamment le décret du 17 mars 1967.",
  "Le contrat de gestion a pour objectif de définir les obligations et missions confiées par l’ASL ou l’AFUL des copropriétaires à la SARL REAL 31, consécutivement au mandat donné par l’assemblée générale en date du [DateAG] etde fixer les modalités de rémunérations du gestionnaire.",
  "1. Missions",
  "L’ASL ou l’AFUL confie à la SARL REAL 31, qui accepte, les fonctions de président de l’ASL ou de l’AFUL ci-dessus mentionnée, conformément à son objet social défini dans les statuts et dans le cadre de l’ordonnance du 1er juillet 2004 et du décret du 3 mai 2006, aux clauses et conditions ci-après définies.",
  "2. Durée du contrat",
  "Le présent contrat est conclu pour une durée de [DureeContrat].",
  "Il prendra effet le [DebutContrat] et prendra fin le [FinContrat].",
  "Il n’est pas renouvelable par tacite reconduction.",
  "3. RESILIATION DU CONTRAT",
  "Le présent contrat pourra être résilié par chacune des parties au moins trois mois avant la date d’échéance par lettre recommandée avec accusé de réception.",
  "En cas de résiliation avant l’échéance, les articles 2004 et 2007 du Code civil s’appliqueront.",
  "4. Prestations et modalités de rémunération du gestionnaire de l’ASL OU DE L’AFUL",
  "Les jours et heures ouvrables de référence pour la détermination des modalités de rémunération sont fixés comme suit :",
  "Du lundi au Vendredi de 9h30 à 12h30 et de 14h00 à 18h00;",
  "Le samedi de 9h30 à 12h30 et de 14h à 16h.",
  "Sauf en cas d’urgence, les démarches individuelles de chaque membre de l’ASL ou de l’AFUL auprès du gestionnaire de l’ASL ou d’AFUL s’effectuent aux jours et heures suivantes (accueil physique et/ou téléphonique effectif) :",
  "Accueil physique :",
  "Du lundi au Vendredi de 9h30 à 12h30 et de 14h00 à 18h00;",
  "Le samedi de 9h30 à 12h30 et de 14h à 16h.",
  "Accueil téléphonique :",
  "Du lundi au Vendredi de 9h30 à 12h30 et de 14h00 à 18h00;",
  "Le samedi de 9h30 à 12h30 et de 14h à 16h.",
  "La rémunération du gestionnaire est déterminée de manière forfaitaire.",
  "Toutefois, une rémunération spécifique peut être perçue en contrepartie des prestations particulières limitativement dans les conditions stipulées au 4.2 du présent contrat.",
  "4.1. Le forfait",
  "4.1.1. Contenu du forfait",
  "Le forfait convenu entre les parties comprend toutes les prestations fournies par le gestionnaire au titre de sa mission, à l’exclusion des prestations limitativement énumérées dans les conditions stipulées au 4.2 du présent contrat. A ce titre, il effectue les visites et vérifications périodiques de l’ensemble immobilier impliquées par la mission relative à l’administration, à la conservation, à la garde et à l’entretien de l’ensemble immobilier. Il est convenu la réalisation, au minimum, de :",
  "- [Coproprietes.NbVisite] visite(s) et vérification(s) périodique(s) de l’ASL ou de l’AFUL, d’une durée de 1 heure, avec rédaction d’un rapport une fois par an.",
  "Une liste non limitative des prestations incluses dans le forfait est annexée au présent contrat.",
  "Les frais de reprographie, les frais d’affranchissement et les frais administratifs afférents aux prestations du forfait sont inclus dans la rémunération forfaitaire.",
  "Ne donnent lieu à aucune rémunération supplémentaire et sont comprises dans la rémunération forfaitaire :",
  "- les formalités de déclaration de sinistre concernant les parties communes et les parties privatives quand le sinistre a sa source dans les parties communes ;",
  "- la gestion des règlements aux bénéficiaires.",
  "4.1.2. Précisions concernant la tenue de l’assemblée générale annuelle",
  "Les parties conviennent que l’assemblée générale annuelle sera tenue pour une durée de [Coproprietes.DureeAG] heures à l’intérieur d’une plage horaire allant de 10 heures à 12h00 et de 14h00 à [Coproprietes.FinMaxAG] heures du Lundi au Vendredi, par le gestionnaire ou un de ses préposés",
  "4.1.3. Prestations optionnelles qui peuvent être incluses dans le forfait sur décision des parties",
  "Le forfait convenu entre les parties en vertu du présent contrat pourra expressément inclure l’une ou plusieurs des prestations suivantes:",
  "4.1.4. Modalités de rémunération",
  "La rémunération forfaitaire annuelle perçue par le gestionnaire au titre du présent contrat s’élève à la somme de [HonoGestionHT] € hors taxes, soit [FormulaireContratSyndic.HonoGestion] € toutes taxes comprises. Cette rémunération est payable trimestriellement d’avance.",
  "Les dépassements des horaires et durées convenus pour la tenue des assemblées générales, réunions et visites/vérifications périodiques incluses dans le forfait sont facturés selon le coût horaire mentionné au 4.2.1.",
  "L’envoi des documents afférents aux prestations du forfait ne donne lieu à aucun remboursement au gestionnaire des frais d’affranchissement ou d’acheminement engagés qui sont inclus dans la rémunération forfaitaire.",
  "4.2. Les prestations particulières pouvant donner lieu à rémunération complémentaire",
  "4.2.1. Modalités de rémunération des prestations particulières",
  "La rémunération due au syndic professionnel au titre des prestations particulières est calculée :",
  "- soit en application du coût horaire ci-dessous :",
  "[TauxHoraireHT] € HT / heure, soit [Tarifs.Tarif.TauxHoraire] € TTC / heure. La facturation se fait à la demi-heure. Toute demi-heure commencée étant due.",
  "- soit en application du tarif convenu par les parties pour chaque prestation particulière.",
  "La rémunération due au titre des prestations particulières s’entend frais d’envoi compris. L’envoi des documents afférents aux prestations particulières ne donne lieu à aucun remboursement au syndic des frais d’affranchissement ou d’acheminement engagés qui sont inclus dans la rémunération forfaitaire.",
  "4.2.2. Prestations relatives aux réunions et visites supplémentaires (au-delà du contenu du forfait stipulé aux 4.1.1 et 4.1.3)",
  [{"texte":"DÉTAIL DE LA PRESTATION","largeur":7},{"texte":"MODALITÉS DE TARIFICATION\nConvenues","largeur":5}],
  [{"texte":"La préparation, la convocation et la tenue d’une assemblée générale supplémentaire de 2 heures, à l’intérieur d’une plage horaire allant de 10 heures à  20 heures","largeur":7},{"texte":"Tarif horaire indiqué au 4.2.1","largeur":5}],
  [{"texte":"L’organisation d’une réunion supplémentaire d’une durée de 1 heure, par rapport à celle incluse dans le forfait au titre du 4.1.3","largeur":7},{"texte":"[CsSuppHT] € HT soit [Tarifs.Tarif.CsSupp] € TTC. Tout dépassement d’horaire sera facturé suivant tarif énoncé au 4.2.1.","largeur":5}],
  [{"texte":"La réalisation d’une visite supplémentaire de l’ASL ou de l’AFUL d’une durée d’une heure, avec rédaction d’un rapport (par rapport à celles incluses dans le forfait au titre du 4.1.1","largeur":7},{"texte":"[VisiteSuppHT] € HT soit [Tarifs.Tarif.VisiteSupp] € TTC. Tout dépassement d’horaire sera facturé suivant tarif énoncé au 4.2.1.","largeur":5}],
  "4.2.3. Prestations relatives aux statuts et à l’état descriptif de division",
  [{"texte":"DÉTAIL DE LA PRESTATION","largeur":7},{"texte":"MODALITÉS DE TARIFICATION\nconvenues","largeur":5}],
  [{"texte":"L’établissement ou la modification des statuts à la suite d’une décision des membres de l’ASL ou de l’AFUL","largeur":7},{"texte":"Le montant des honoraires sera fixé lors de la décision de l’assemblée générale.","largeur":5}],
  [{"texte":"La publication des modifications apportées à ces actes","largeur":7},{"texte":"[PublicationStatutsHT] € HT soit [Tarifs.Tarif.PublicationStatuts] € TTC par volume.","largeur":5}],
  "4.2.4. Prestations de gestion administrative et matérielle relatives aux sinistres",
  [{"texte":"DÉTAIL DE LA PRESTATION","largeur":7},{"texte":"MODALITÉS DE TARIFICATION\nconvenues","largeur":5}],
  [{"texte":"Les déplacements sur les lieux","largeur":7},{"texte":"[DepLieuHT] € HT soit [Tarifs.Tarif.DepLieu] € TTC.","largeur":5}],
  [{"texte":"La prise de mesures conservatoires","largeur":7},{"texte":"[MesConserHT] € HT soit [Tarifs.Tarif.MesConser] € TTC.","largeur":5}],
  [{"texte":"L’assistance aux mesures d’expertise","largeur":7},{"texte":"[AssExpHT] € HT soit [Tarifs.Tarif.AssExp] € TTC.","largeur":5}],
  [{"texte":"Le suivi du dossier auprès de l’assureur","largeur":7},{"texte":"[DossierAssureurHT] € HT soit [Tarifs.Tarif.DossierAssureur] € TTC.","largeur":5}],
  "Les prestations effectuées en dehors des jours et heures ouvrables et rendues nécessaires par l’urgence sont facturées au coût horaire majoré de 40%.",
  "Toute somme versée par l’assureur au gestionnaire au titre de la couverture des diligences effectuées par ce dernier dans le cadre du règlement d’un sinistre vient en déduction de la rémunération due en application du présent article.",
  "4.2.5. Prestations relatives aux travaux et études techniques",
  "Les travaux votés en assemblée générale peuvent faire l’objet d’honoraires spécifiques.",
  "Ces honoraires concernent :",
  "- les travaux de conservation ou d’entretien de l’immeuble, autres que ceux de maintenance ou d’entretien courant ;",
  "- les travaux portant sur les éléments d’équipement communs, autres que ceux de maintenance ;",
  "- les travaux d’amélioration, tels que la transformation d’un ou de plusieurs éléments d’équipement existants, l’adjonction d’éléments nouveaux, l’aménagement de locaux affectés à l’usage commun ou la création de tels locaux, l’affouillement du sol et la surélévation de bâtiments ;",
  "- les études techniques, telles que les diagnostics et consultations ;",
  "- d’une manière générale, les travaux qui ne concourent pas à la maintenance et à l’administration des parties communes ou à la maintenance et au fonctionnement des équipements communs de l’immeuble.",
  "Les honoraires complémentaires éventuels sont votés lors de la même assemblée générale que les travaux concernés et aux mêmes règles de majorité.",
  "Le présent contrat ne peut se lire comme fixant un barème relatif à ces honoraires spécifiques, même à titre indicatif.",
  "Une telle rémunération fixée dans le projet de résolution soumis au vote de l’assemblée générale doit être exprimée en pourcentage du montant hors taxes des travaux, à un taux dégressif selon l’importance des travaux préalablement à leur exécution.",
  "Le choix du prestataire par l’assemblée générale est précédé d’une mise en concurrence.",
  "Les diligences entreprises par le gestionnaire de l’ASL ou de l’AFUL dans le cadre de la réalisation du diagnostic de performance énergétique collectif et de l’audit énergétique peuvent donner lieu à rémunération dans les conditions prévues au présent article.",
  "4.2.6. Prestations relatives aux litiges et contentieux (hors frais de recouvrement visés au point 5.1)",
  [{"texte":"DÉTAIL DE LA PRESTATION","largeur":7},{"texte":"MODALITÉS DE TARIFICATION\nconvenues","largeur":5}],
  [{"texte":"La mise en demeure d’un tiers par lettre recommandée avec accusé de réception","largeur":7},{"texte":"[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC.","largeur":5}],
  [{"texte":"La constitution du dossier transmis à l’avocat, à l’huissier de justice ou à l’assureur protection juridique (à l’exclusion des formalités visées au 5.2.4)","largeur":7},{"texte":"[DossierAvocatHT] € HT soit [Tarifs.Tarif.DossierAvocat] € TTC.","largeur":5}],
  [{"texte":"Le suivi du dossier transmis à l’avocat","largeur":7},{"texte":"Tarif horaire indiqué au 5.2.1","largeur":5}],
  "4.2.7. Autres prestations",
  [{"texte":"DÉTAIL DE LA PRESTATION","largeur":7},{"texte":"MODALITÉS DE TARIFICATION\nconvenues","largeur":5}],
  [{"texte":"Les diligences spécifiquement liées à la préparation des décisions d’acquisition ou de disposition des parties communes","largeur":7},{"texte":"Le montant des honoraires sera fixé lors de la décision de l’assemblée générale confiant au gestionnaire les prestations concernées","largeur":5}],
  [{"texte":"La reprise de la comptabilité sur exercice(s) antérieur(s) non approuvés ou non répartis (changement de gestionnaire)","largeur":7},{"texte":"Tarif horaire indiqué au 4.2.1","largeur":5}],
  [{"texte":"La constitution et le suivi du dossier d’emprunt souscrit au nom de l’ASL ou de l’AFUL","largeur":7},{"texte":"Tarif horaire indiqué au 4.2.1","largeur":5}],
  [{"texte":"La constitution et le suivi d’un dossier de subvention accordé à l’ASL ou de l’AFUL","largeur":7},{"texte":"Tarif horaire indiqué au 4.2.1","largeur":5}],
  [{"texte":"L’immatriculation initiale de l’ASL ou de l’AFUL","largeur":7},{"texte":"[ImmatInitialeHT] € HT soit [Tarifs.Tarif.ImmatInitiale] € TTC","largeur":5}],
  "5. Frais et honoraires imputables aux seuls membres",
  "Le coût des prestations suivantes est imputable au seul membre concerné et non à l’ASL ou à l’AFUL qui ne peut être tenue d’aucune somme à ce titre.",
  [{"texte":"PRESTATIONS","largeur":4},{"texte":"DÉTAILS","largeur":4},{"texte":"TARIFICATION PRATIQUÉE","largeur":4}],
  [{"texte":"5.1. Frais de recouvrement","largeur":4},{"texte":"Mise en demeure par lettre recommandée avec accusé de réception ;\nRelance après mise en demeure :\nConclusion d’un protocole d’accord par acte sous seing privé ;\nFrais de constitution d’hypothèque prévue par l’article 6 dernier alinéa de l’ordonnance du 1er juillet 2004;\nFrais de mainlevée d’hypothèque prévue par l’article 6 dernier alinéa de l’ordonnance du 1er juillet 2004;\nDépôt d’une requête en injonction de payer ;\nConstitution du dossier transmis à l’auxiliaire de justice ;\nSuivi du dossier transmis à l’avocat (uniquement en cas de diligences exceptionnelles)","largeur":4},{"texte":"[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC.\n[MEDHT] € HT soit [Tarifs.Tarif.MED] € TTC.\n[EcheancierHT] € HT soit [Tarifs.Tarif.Echeancier] € TTC.\n[HypothequeHT] € HT soit [Tarifs.Tarif.Hypotheque] € TTC.\n[HypothequeHT] € HT soit [Tarifs.Tarif.Hypotheque] € TTC.\n[InjonctionHT] € HT soit [Tarifs.Tarif.Injonction] € TTC.\n[DossierJusticeHT] € HT soit [Tarifs.Tarif.DossierJustice] € TTC.\nTarif horaire indiqué au 4.2.1","largeur":4}],
  [{"texte":"5.2. Frais et honoraires liés aux mutations","largeur":4},{"texte":"Etablissement de l’état daté prévu par l’article 3 dernier alinéa de l’ordonnance du 1er juillet 2004 ;\nOpposition sur mutation ;","largeur":4},{"texte":"[EtatDateHT] € HT soit [Tarifs.Tarif.EtatDate] € TTC.\n[OppositionHT] € HT soit [Tarifs.Tarif.Opposition] € TTC.","largeur":4}],
  [{"texte":"PRESTATIONS","largeur":4},{"texte":"DÉTAILS","largeur":4},{"texte":"TARIFICATION PRATIQUÉE","largeur":4}],
  [{"texte":"5.3 Frais de délivrance des documents sur support papier (art. 33 du décret du 17 mars 1967 et R. 134-3 du code de la construction et de l’habitation)","largeur":4},{"texte":"Délivrance d’une copie du carnet d’entretien ;\nDélivrance d’une copie des diagnostics techniques;\nDélivrance des informations nécessaires à la réalisation d’un diagnostic de performance énergétique individuel mentionnées à l’article R. 134-3 du code de la construction et de l’habitation ;\nDélivrance au membre d’une copie certifiée conforme ou d’un extrait de procès-verbal d’assemblée générale ainsi que des copies et annexes","largeur":4},{"texte":"[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC.\n[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC\n[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC\n[DelivranceCopieHT] € HT soit [Tarifs.Tarif.DelivranceCopie] € TTC","largeur":4}],
  "6. MODALITES de gestion bancaire et financiere des fonds de l’asl OU DE L’AFUL",
  "Les fonds versés par les membres de l’ASL ou de l’AFUL au titre des charges ou travaux seront déposés sur un compte bancaire ouvert au nom de l’ASL ou de l’AFUL dont les intérêts reviendront à l’ASL ou à l’AFUL.",
  "Les frais de gestion de ce compte seront à la charge de l’ASL ou de l’AFUL.",
  "7. Reddition de compte",
  "La reddition de compte interviendra chaque année à la date ou selon la périodicité suivante : dans les 6 mois qui suivent la clôture de l’exercice. La répartition individuelle (régularisation des charges) sur le compte de chaque membre interviendra chaque année dans les deux mois suivant l’Assemblée Générale statuant sur les comptes de l’exercice écoulé.",
  "8. MODALITES DE REVISION DE LA REMUNERATION",
  "La rémunération du gestionnaire de l’ASL ou de l’AFUL sera revotée à chaque assemblée annuelle par les membres de l’[FormeJuridique].",
  "Aucune formule de révision n’est prévue.",
  "9. Compétence",
  "Tous les litiges nés de l’exécution du présent contrat sont de la compétence de la juridiction du lieu de situation de l’ensemble immobilier.",
  "Les parties élisent domicile aux fins des présentes, aux adresses ci-dessous :",
  "Pour l’[FormeJuridique] : A l’adresse stipulée dans les statuts.",
  "Pour le gestionnaire : A l’adresse de ses bureaux.",
  "Fait en deux exemplaires et signé ce jour, le [DateAG] à",
  "Mots nuls …",
  "Lignes nulles …",
  [{"texte":"Le représentant de l’[FormeJuridique]","largeur":6},{"texte":"Le gestionnaire de l’[FormeJuridique]","largeur":6}],
] as const;

/** Tous les placeholders du gabarit, pour le test de couverture. */
export const PLACEHOLDERS_MANDAT: readonly string[] = [
  "[AssExpHT]",
  "[Coproprietes.Adresse1]",
  "[Coproprietes.Adresse2]",
  "[Coproprietes.Adresse3]",
  "[Coproprietes.Agence]",
  "[Coproprietes.CP]",
  "[Coproprietes.Denomination]",
  "[Coproprietes.DureeAG]",
  "[Coproprietes.FinMaxAG]",
  "[Coproprietes.NbVisite]",
  "[Coproprietes.Ville]",
  "[CsSuppHT]",
  "[DateAG]",
  "[DebutContrat]",
  "[DelivranceCopieHT]",
  "[DepLieuHT]",
  "[DossierAssureurHT]",
  "[DossierAvocatHT]",
  "[DossierJusticeHT]",
  "[DureeContrat]",
  "[EcheancierHT]",
  "[EtatDateHT]",
  "[FinContrat]",
  "[FormeJuridique]",
  "[FormulaireContratSyndic.HonoGestion]",
  "[HonoGestionHT]",
  "[HypothequeHT]",
  "[ImmatInitialeHT]",
  "[InjonctionHT]",
  "[MEDHT]",
  "[MesConserHT]",
  "[OppositionHT]",
  "[PublicationStatutsHT]",
  "[Tarifs.Tarif.AssExp]",
  "[Tarifs.Tarif.CsSupp]",
  "[Tarifs.Tarif.DelivranceCopie]",
  "[Tarifs.Tarif.DepLieu]",
  "[Tarifs.Tarif.DossierAssureur]",
  "[Tarifs.Tarif.DossierAvocat]",
  "[Tarifs.Tarif.DossierJustice]",
  "[Tarifs.Tarif.Echeancier]",
  "[Tarifs.Tarif.EtatDate]",
  "[Tarifs.Tarif.Hypotheque]",
  "[Tarifs.Tarif.ImmatInitiale]",
  "[Tarifs.Tarif.Injonction]",
  "[Tarifs.Tarif.MED]",
  "[Tarifs.Tarif.MesConser]",
  "[Tarifs.Tarif.Opposition]",
  "[Tarifs.Tarif.PublicationStatuts]",
  "[Tarifs.Tarif.TauxHoraire]",
  "[Tarifs.Tarif.VisiteSupp]",
  "[TauxHoraireHT]",
  "[VisiteSuppHT]",
] as const;
